csp = {
    "default-src": ["'self'"],
    "style-src": ["'self'", "'unsafe-inline'", "cse.google.com", "www.google.com"],
    "script-src": [
        "'self'",
        "'strict-dynamic'",
        "*.google-analytics.com",
        "www.googletagmanager.com",
        "cse.google.com",
        "'unsafe-inline'",
        "'unsafe-eval'",
    ],
    "font-src": ["'self'"],
    "connect-src": [
        "'self'",
        "*.google-analytics.com",
        "www.googletagmanager.com",
        "ep1.adtrafficquality.google",
    ],
    "img-src": [
        "'self'",
        "*.google-analytics.com",
        "www.google.com",
        "www.googletagmanager.com",
        "www.googleapis.com",
        "*.google.com",
        "*.gstatic.com",
        "ssl.gstatic.com",
        "data:",
    ],
    "frame-src": [
        "'self'",
        "cse.google.com",
        "syndicatedsearch.goog",
        "www.googletagmanager.com",
    ],
    "object-src": ["'none'"],
    "base-uri": ["'none'"],
}
