version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "npm"
    directory: "/src/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "prettier"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "pip"
    directory: "/src/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    cooldown:
      default-days: 7


