version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "prettier"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "pip"
    directory: "/src/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
