#standardSQL
# List all included government domains along with scores

WITH score_data AS (
  SELECT
    client,
    CAST(JSON_EXTRACT_SCALAR(lighthouse, '$.categories.performance.score') AS FLOAT64) AS performance_score,
    CAST(JSON_EXTRACT_SCALAR(lighthouse, '$.categories.accessibility.score') AS FLOAT64) AS accessibility_score,
    CAST(JSON_EXTRACT_SCALAR(lighthouse, '$.categories.best-practices.score') AS FLOAT64) AS best_practices_score,
    CAST(JSON_EXTRACT_SCALAR(lighthouse, '$.categories.seo.score') AS FLOAT64) AS seo_score,
    page,
    is_root_page,
    wptid
  FROM
    `httparchive.all.pages`
  WHERE
    date = '2024-06-01' AND
    lighthouse IS NOT NULL AND
    lighthouse != '{}'
),

domain_scores AS (
  SELECT
    page,
    CASE
      -- United Nations
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.un\\.org(/|$)|\\.worldbank.org(/|$)|\\.undp.org(/|$)|\\.reliefweb.int(/|$)|\\.who.int(/|$)|\\.unfccc.int(/|$)|\\.unccd.int(/|$)|\\.unesco.org(/|$)') THEN 'United Nations'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.europa\\.eu(/|$)') THEN 'European Union'

      -- USA State Governments (must come before federal .gov check)
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.alabama\\.gov(/|$)|\\.Al\\.gov(/|$)') THEN 'Alabama'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.alaska\\.gov(/|$)|\\.Ak\\.gov(/|$)') THEN 'Alaska'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.arizona\\.gov(/|$)|\\.AZ\.gov(/|$)') THEN 'Arizona'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.arkansas\\.gov(/|$)|\\.Ar\\.gov(/|$)') THEN 'Arkansas'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.california\\.gov(/|$)|\\.Ca\\.gov(/|$)') THEN 'California'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.colorado\\.gov(/|$)|\\.Co\\.gov(/|$)') THEN 'Colorado'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.connecticut\\.gov(/|$)|\\.Ct\\.gov(/|$)') THEN 'Connecticut'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.delaware\\.gov(/|$)|\\.De\\.gov(/|$)') THEN 'Delaware'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.florida\\.gov(/|$)|\\.Fl\\.gov(/|$)|\\.myflorida\\.com(/|$)') THEN 'Florida'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.georgia\\.gov(/|$)|\\.Ga\\.gov(/|$)') THEN 'Georgia State' -- To avoid confusion with the country
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.hawaii\\.gov(/|$)|\\.hi\\.gov(/|$)|\\.ehawaii\\.gov(/|$)') THEN 'Hawaii'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.idaho\\.gov(/|$)|\\.id\\.gov(/|$)') THEN 'Idaho'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.illinois\\.gov(/|$)|\\.Il\\.gov(/|$)') THEN 'Illinois'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.indiana\\.gov(/|$)|\\.in\\.gov(/|$)') THEN 'Indiana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.iowa\\.gov(/|$)|\\.ia\\.gov(/|$)') THEN 'Iowa'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kansas\\.gov(/|$)|\\.Ks\\.gov(/|$)') THEN 'Kansas'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kentucky\\.gov(/|$)|\\.Ky\\.gov(/|$)') THEN 'Kentucky'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.louisiana\\.gov(/|$)|\\.La\\.gov(/|$)') THEN 'Louisiana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.maine\\.gov(/|$)|\\.Me\\.gov(/|$)') THEN 'Maine'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.maryland\\.gov(/|$)|\\.Md\\.gov(/|$)') THEN 'Maryland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.massachusetts\\.gov(/|$)|\\.Ma\\.gov(/|$)|\\.mass\\.gov(/|$)') THEN 'Massachusetts'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.michigan\\.gov(/|$)|\\.Mi\\.gov(/|$)') THEN 'Michigan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.minnesota\\.gov(/|$)|\\.Mn\\.gov(/|$)') THEN 'Minnesota'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mississippi\\.gov(/|$)|\\.Ms\\.gov(/|$)') THEN 'Mississippi'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.missouri\\.gov(/|$)|\\.Mo\\.gov(/|$)') THEN 'Missouri'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.montana\\.gov(/|$)|\\.Mt\\.gov(/|$)') THEN 'Montana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nebraska\\.gov(/|$)|\\.Ne\\.gov(/|$)') THEN 'Nebraska'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nevada\\.gov(/|$)|\\.Nv\\.gov(/|$)') THEN 'Nevada'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.newhampshire\\.gov(/|$)|\\.NH\.gov(/|$)') THEN 'New Hampshire'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.newjersey\\.gov(/|$)|\\.NJ\.gov(/|$)') THEN 'New Jersey'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.newmexico\\.gov(/|$)|\\.Nm\\.gov(/|$)') THEN 'New Mexico'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.newyork\\.gov(/|$)|\\.Ny\\.gov(/|$)') THEN 'New York'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.northcarolina\\.gov(/|$)|\\.Nc\\.gov(/|$)') THEN 'North Carolina'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.northdakota\\.gov(/|$)|\\.Nd\\.gov(/|$)') THEN 'North Dakota'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ohio\\.gov(/|$)|\\.OH\.gov(/|$)') THEN 'Ohio'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.oklahoma\\.gov(/|$)|\\.Ok\\.gov(/|$)') THEN 'Oklahoma'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.oregon\\.gov(/|$)|\\.Or\\.gov(/|$)') THEN 'Oregon'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pennsylvania\\.gov(/|$)|\\.Pa\\.gov(/|$)') THEN 'Pennsylvania'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.rhodeisland\\.gov(/|$)|\\.Ri\\.gov(/|$)') THEN 'Rhode Island'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.southcarolina\\.gov(/|$)|\\.Sc\\.gov(/|$)') THEN 'South Carolina'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.southdakota\\.gov(/|$)|\\.Sd\\.gov(/|$)') THEN 'South Dakota'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tennessee\\.gov(/|$)|\\.Tn\\.gov(/|$)') THEN 'Tennessee'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.texas\\.gov(/|$)|\\.TX\.gov(/|$)') THEN 'Texas'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.utah\.gov(/|$)|\\.Ut\\.gov(/|$)') THEN 'Utah'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.vermont\\.gov(/|$)|\\.Vt\\.gov(/|$)') THEN 'Vermont'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.virginia\\.gov(/|$)') THEN 'Virginia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.washington\\.gov(/|$)|\\.Wa\\.gov(/|$)') THEN 'Washington'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.westvirginia\\.gov(/|$)|\\.Wv\\.gov(/|$)') THEN 'West Virginia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.wisconsin\\.gov(/|$)|\\.Wi\\.gov(/|$)') THEN 'Wisconsin'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.wyoming\\.gov(/|$)|\\.Wy\\.gov(/|$)') THEN 'Wyoming'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.dc\\.gov(/|$)') THEN 'DC'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pr\\.gov(/|$)') THEN 'Puerto Rico'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.guam\\.gov(/|$)') THEN 'Guam'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.americansamoa\\.gov(/|$)') THEN 'American Samoa'

      -- North American Federal Governments
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.va\\.gov(/|$)') THEN 'USA VA.gov'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cms\\.gov(/|$)') THEN 'USA CMS.gov'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov(/|$)|(?i)\\.us(/|$)') THEN 'United States (USA)' -- States and specific departments are listed first to make them distinct.
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mil(/|$)') THEN 'USA Military'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gob\\.mx(/|$)') THEN 'Mexico'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gc\\.ca(/|$)|\\.canada\\.ca(/|$)|\\.alberta\\.ca(/|$)|\\.gov\\.ab\\.ca(/|$)|\\.gov\\.bc\\.ca(/|$)|\\.manitoba\\.ca(/|$)|\\.gov\\.mb\\.ca(/|$)|\\.gnb\\.ca(/|$)|\\.gov\\.nb\\.ca(/|$)|\\.gov\\.nl\\.ca(/|$)|\\.novascotia\\.ca(/|$)|\\.gov\\.ns\\.ca(/|$)|\\.ontario\\.ca(/|$)|\\.gov\\.on\\.ca(/|$)|\\.gov\\.pe\\.ca(/|$)|\\.quebec\\.ca(/|$)|\\.gouv\\.qc\\.ca(/|$)|\\.revenuquebec\\.ca(/|$)|\\.saskatchewan\\.ca(/|$)|\\.gov\\.sk\\.ca(/|$)|\\.gov\\.nt\\.ca(/|$)|\\.gov\\.nu\.ca(/|$)|\\.yukon\\.ca(/|$)|\\.gov\\.yk\\.ca') THEN 'Canada'

      -- European Countries
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.al(/|$)') THEN 'Albania'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ax(/|$)') THEN 'Åland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.ad(/|$)|\\.govern\\.ad(/|$)|\\.exteriors\\.ad(/|$)|\\.consellgeneral\\.ad(/|$)') THEN 'Andorra'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.am(/|$)') THEN 'Armenia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gv\\.at(/|$)') THEN 'Austria'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.az(/|$)') THEN 'Azerbaijan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.eus(/|$)') THEN 'Basque Country'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.by(/|$)') THEN 'Belarus'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.belgium\\.be(/|$)|\\.gov\\.be/\.fgov\\.be(/|$)|\\.vlaanderen\\.be(/|$)|\\.wallonie\\.be(/|$)|\\.brussels\\.be(/|$)|\\.mil\\.be(/|$)') THEN 'Belgium'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ba(/|$)') THEN 'Bosnia and Herzegovina'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.government\\.bg(/|$)') THEN 'Bulgaria'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.hr(/|$)') THEN 'Croatia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cy(/|$)') THEN 'Cyprus'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.cz(/|$)') THEN 'Czechia (Czech Republic)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.dk(/|$)|\\.ft\\.dk(/|$)|\\.nemkonto\\.dk(/|$)|\\.nemlog-in\\.dk(/|$)|\\.mitid\\.dk(/|$)|\\.digst\\.dk(/|$)|\\.sikkerdigital\\.dk(/|$)|\\.forsvaret\\.dk(/|$)|\\.skat\\.dk(/|$)|\\.stps\\.dk(/|$)|\\.ufm\\.dk(/|$)|\\.urm\\.dk(/|$)|\\.uvm\\.dk(/|$)|\\.politi\\.dk(/|$)|\\.dataetiskraad\\.dk(/|$)|\\.at\\.dk(/|$)|\\.kum\\.dk(/|$)') THEN 'Denmark'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.riik\\.ee(/|$)|\\.riigiteataja\\.ee(/|$)|\\.eesti\\.ee(/|$)|\\.valitsus\\.ee(/|$)') THEN 'Estonia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.fi/|(?i)\\.valtioneuvosto\\.fi/|(?i)\\.minedu\.fi/|(?i)\\.formin\\.fi/|(?i)\\.intermin\\.fi/|(?i)\\.suomi\\.fi/|(?i)\\.ym\\.fi/|(?i)\\.stm\\.fi/|(?i)\\.tem\\.fi/|(?i)\\.lvm\\.fi/|(?i)\\.mmm\\.fi/|(?i)\\.okm\\.fi/|(?i)\\.vm\\.fi/|(?i)\\.defmin\\.fi/|(?i)\\.oikeusministerio\\.fi/|(?i)\\.um\\.fi/|(?i)\\.vero\\.fi/|(?i)\\.kela\\.fi(/|(?i)\\.$)') THEN 'Finland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gouv\\.fr(/|$)') THEN 'France'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.ge(/|$)') THEN 'Georgia Country'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bund\\.de(/|$)') THEN 'Germany'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gi(/|$)') THEN 'Gibraltar'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.gr(/|$)') THEN 'Greece'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.hu(/|$)') THEN 'Hungary'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.is(/|$)') THEN 'Iceland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.ie(/|$)') THEN 'Ireland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.im(/|$)') THEN 'Isle of Man'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.it/|governo.it(/|$)') THEN 'Italy'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kz(/|$)') THEN 'Kazakhstan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.lv(/|$)') THEN 'Latvia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.li(/|$)') THEN 'Liechtenstein'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.lt(/|$)|\\.vrm\\.lt(/|$)|\\.sam\\.lt(/|$)|\\.ukmin\\.lt(/|$)|\\.lrv\\.lt(/|$)|\\.uzt\\.lt(/|$)|\\.migracija\\.lt(/|$)|\\.kam\\.lt(/|$)|\\.lrs\\.lt(/|$)|\\.urm\\.lt(/|$)') THEN 'Lithuania'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.public\\.lu(/|$)|\\.etat\\.lu(/|$)') THEN 'Luxembourg'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mt(/|$)') THEN 'Malta'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.md(/|$)') THEN 'Moldova'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mc(/|$)') THEN 'Monaco'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.me(/|$)') THEN 'Montenegro'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.nl(/|$)|\\.overheid\\.nl(/|$)|\\.mijnoverheid\\.nl(/|$)') THEN 'Netherlands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mk(/|$)') THEN 'Macedonia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.no(/|$)') THEN 'Norway'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.pl(/|$)') THEN 'Poland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.pt(/|$)') THEN 'Portugal'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ro(/|$)') THEN 'Romania'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.ru|\\.govvrn\\.ru(/|$)') THEN 'Russia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sm(/|$)') THEN 'San Marino'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.rs(/|$)') THEN 'Serbia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.sk(/|$)') THEN 'Slovakia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.si(/|$)') THEN 'Slovenia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.es|gob\\.es|ine\\.es|boe\\.es(/|$)') THEN 'Spain'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sj(/|$)') THEN 'Svalbard and Jan Mayen Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.se/|1177\.se/|funktionstjanster\\.se/|hemnet\\.se/|smhi\\.se/|sverigesradio\\.se/|klart\\.se/|bankid\\.com/|synonymer\\.se/|arbetsformedlingen\\.se/|skatteverket\\.se/|schoolsoft\\.se/|postnord\\.se/|grandid\\.com/|viaplay\\.se/|skola24\.se/|forsakringskassan\\.se/|vklass\\.se|sl\\.se/|familjeliv\\.se(/|$)') THEN 'Sweden'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.admin\\.ch(/|$)') THEN 'Switzerland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gv\\.ua(/|$)') THEN 'Ukraine'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.uk(/|$)') THEN 'United Kingdom (UK)'

      -- Other Countries
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.af(/|$)') THEN 'Afghanistan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.dz(/|$)') THEN 'Algeria'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.as(/|$)') THEN 'American Samoa'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ao(/|$)') THEN 'Angola'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ai(/|$)') THEN 'Anguilla'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.aq(/|$)') THEN 'Antarctica'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ag(/|$)') THEN 'Antigua and Barbuda'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gub\\.ar(/|$)|\\.gov\\.ar(/|$)') THEN 'Argentina'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.aw(/|$)') THEN 'Aruba'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ac(/|$)') THEN 'Ascension Island'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.au(/|$)') THEN 'Australia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bs(/|$)') THEN 'Bahamas'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bh(/|$)') THEN 'Bahrain'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bd(/|$)') THEN 'Bangladesh'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bb(/|$)') THEN 'Barbados'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bz(/|$)') THEN 'Belize'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bj(/|$)') THEN 'Benin'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bm(/|$)') THEN 'Bermuda'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bt(/|$)') THEN 'Bhutan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bo(/|$)') THEN 'Bolivia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bq(/|$)') THEN 'Bonaire'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.an(/|$)') THEN 'Bonaire'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nl(/|$)') THEN 'Bonaire'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bw(/|$)') THEN 'Botswana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bv(/|$)') THEN 'Bouvet Island'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.br(/|$)') THEN 'Brazil'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.io(/|$)') THEN 'British Indian Ocean Territory'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.vg(/|$)') THEN 'British Virgin Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bn(/|$)') THEN 'Brunei'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bf(/|$)') THEN 'Burkina Faso'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mm(/|$)') THEN 'Burma (officially: Myanmar)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bi(/|$)') THEN 'Burundi'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kh(/|$)') THEN 'Cambodia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cm(/|$)') THEN 'Cameroon'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ca(/|$)') THEN 'Canada'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cv(/|$)') THEN 'Cape Verde (in Portuguese: Cabo Verde)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cat(/|$)') THEN 'Catalonia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ky(/|$)') THEN 'Cayman Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cf(/|$)') THEN 'Central African Republic'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.td(/|$)') THEN 'Chad'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cl(/|$)') THEN 'Chile'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cn(/|$)') THEN 'China, People’s Republic of'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cx(/|$)') THEN 'Christmas Island'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cc(/|$)') THEN 'Cocos (Keeling) Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.co(/|$)') THEN 'Colombia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.km(/|$)') THEN 'Comoros'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cd(/|$)') THEN 'Congo, Democratic Republic of the (Congo-Kinshasa)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cg(/|$)') THEN 'Congo, Republic of the (Congo-Brazzaville)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ck(/|$)') THEN 'Cook Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cr(/|$)') THEN 'Costa Rica'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ci(/|$)') THEN 'Côte d’Ivoire (Ivory Coast)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cu(/|$)') THEN 'Cuba'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.cw(/|$)') THEN 'Curaçao'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.dj(/|$)') THEN 'Djibouti'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.dm(/|$)') THEN 'Dominica'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.do(/|$)') THEN 'Dominican Republic'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tl(/|$)') THEN 'East Timor (Timor-Leste)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tp(/|$)') THEN 'East Timor (Timor-Leste)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ec(/|$)') THEN 'Ecuador'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.eg(/|$)') THEN 'Egypt'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sv(/|$)') THEN 'El Salvador'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gq(/|$)') THEN 'Equatorial Guinea'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.er(/|$)') THEN 'Eritrea'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.et(/|$)') THEN 'Ethiopia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.eu(/|$)') THEN 'European Union'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.fk(/|$)') THEN 'Falkland Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.fo(/|$)') THEN 'Faeroe Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.fm(/|$)') THEN 'Federated States of Micronesia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.fj(/|$)') THEN 'Fiji'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gf(/|$)') THEN 'French Guiana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pf(/|$)') THEN 'French Polynesia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tf(/|$)') THEN 'French Southern and Antarctic Lands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ga(/|$)') THEN 'Gabon (officially: Gabonese Republic)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gal(/|$)') THEN 'Galicia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gm(/|$)') THEN 'Gambia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ps(/|$)') THEN 'Gaza Strip (Gaza)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gh(/|$)') THEN 'Ghana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gl(/|$)') THEN 'Greenland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gd(/|$)') THEN 'Grenada'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gp(/|$)') THEN 'Guadeloupe'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gu(/|$)') THEN 'Guam'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gt(/|$)') THEN 'Guatemala'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gg(/|$)') THEN 'Guernsey'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gn(/|$)') THEN 'Guinea'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gw(/|$)') THEN 'Guinea-Bissau'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gy(/|$)') THEN 'Guyana'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ht(/|$)') THEN 'Haiti'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.hm(/|$)') THEN 'Heard Island and McDonald Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.hn(/|$)') THEN 'Honduras'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.hk(/|$)') THEN 'Hong Kong'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gov\\.in(/|$)|\\.nic\\.in(/|$)') THEN 'India'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.id(/|$)') THEN 'Indonesia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ir(/|$)') THEN 'Iran'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.iq(/|$)') THEN 'Iraq'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.il(/|$)') THEN 'Israel'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.it(/|$)') THEN 'Italy'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.jm(/|$)') THEN 'Jamaica'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.jp(/|$)') THEN 'Japan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.je(/|$)') THEN 'Jersey'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.jo(/|$)') THEN 'Jordan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ke(/|$)') THEN 'Kenya'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ki(/|$)') THEN 'Kiribati'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kw(/|$)') THEN 'Kuwait'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kg(/|$)') THEN 'Kyrgyzstan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.la(/|$)') THEN 'Laos'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.lb(/|$)') THEN 'Lebanon'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ls(/|$)') THEN 'Lesotho'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.lr(/|$)') THEN 'Liberia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ly(/|$)') THEN 'Libya'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mo(/|$)') THEN 'Macau'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mg(/|$)') THEN 'Madagascar'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mw(/|$)') THEN 'Malawi'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.my(/|$)') THEN 'Malaysia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mv(/|$)') THEN 'Maldives'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ml(/|$)') THEN 'Mali'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mh(/|$)') THEN 'Marshall Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mq(/|$)') THEN 'Martinique'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mr(/|$)') THEN 'Mauritania'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mu(/|$)') THEN 'Mauritius'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.yt(/|$)') THEN 'Mayotte'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mx(/|$)') THEN 'Mexico'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mn(/|$)') THEN 'Mongolia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ms(/|$)') THEN 'Montserrat'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ma(/|$)') THEN 'Morocco'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mz(/|$)') THEN 'Mozambique'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mm(/|$)') THEN 'Myanmar'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.na(/|$)') THEN 'Namibia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nr(/|$)') THEN 'Nauru'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.np(/|$)') THEN 'Nepal'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nl(/|$)') THEN 'Netherlands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nc(/|$)') THEN 'New Caledonia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nz(/|$)') THEN 'New Zealand'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ni(/|$)') THEN 'Nicaragua'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ne(/|$)') THEN 'Niger'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ng(/|$)') THEN 'Nigeria'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nu(/|$)') THEN 'Niue'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nf(/|$)') THEN 'Norfolk Island'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nc(/|$)') THEN 'North Cyprus (unrecognised, self-declared state)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tr(/|$)') THEN 'North Cyprus (unrecognised, self-declared state)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kp(/|$)') THEN 'North Korea'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mp(/|$)') THEN 'Northern Mariana Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.om(/|$)') THEN 'Oman'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pk(/|$)') THEN 'Pakistan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pw(/|$)') THEN 'Palau'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ps(/|$)') THEN 'Palestine'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pa(/|$)') THEN 'Panama'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pg(/|$)') THEN 'Papua New Guinea'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.py(/|$)') THEN 'Paraguay'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pe(/|$)') THEN 'Peru'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ph(/|$)') THEN 'Philippines'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pn(/|$)') THEN 'Pitcairn Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pr(/|$)') THEN 'Puerto Rico'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.qa(/|$)') THEN 'Qatar'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.rw(/|$)') THEN 'Rwanda'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.re(/|$)') THEN 'Réunion Island'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bq(/|$)') THEN 'Saba'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.an(/|$)') THEN 'Saba'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bl(/|$)') THEN 'Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gp(/|$)') THEN 'Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.fr(/|$)') THEN 'Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sh(/|$)') THEN 'Saint Helena'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kn(/|$)') THEN 'Saint Kitts and Nevis'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.lc(/|$)') THEN 'Saint Lucia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.mf(/|$)') THEN 'Saint Martin (officially the Collectivity of Saint Martin)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gp(/|$)') THEN 'Saint Martin (officially the Collectivity of Saint Martin)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.fr(/|$)') THEN 'Saint Martin (officially the Collectivity of Saint Martin)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.pm(/|$)') THEN 'Saint-Pierre and Miquelon'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.vc(/|$)') THEN 'Saint Vincent and the Grenadines'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ws(/|$)') THEN 'Samoa'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.st(/|$)') THEN 'São Tomé and Príncipe'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sa(/|$)') THEN 'Saudi Arabia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sn(/|$)') THEN 'Senegal'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sc(/|$)') THEN 'Seychelles'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sl(/|$)') THEN 'Sierra Leone'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sg(/|$)') THEN 'Singapore'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.bq(/|$)') THEN 'Sint Eustatius'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.an(/|$)') THEN 'Sint Eustatius'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.nl(/|$)') THEN 'Sint Eustatius'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sx(/|$)') THEN 'Sint Maarten'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.an(/|$)') THEN 'Sint Maarten'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sb(/|$)') THEN 'Solomon Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.so(/|$)') THEN 'Somalia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.so(/|$)') THEN 'Somaliland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.za(/|$)') THEN 'South Africa'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.gs(/|$)') THEN 'South Georgia and the South Sandwich Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.kr(/|$)') THEN 'South Korea'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ss(/|$)') THEN 'South Sudan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.es(/|$)') THEN 'Spain'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.lk(/|$)') THEN 'Sri Lanka'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sd(/|$)') THEN 'Sudan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sr(/|$)') THEN 'Suriname'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sz(/|$)') THEN 'Swaziland'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.se(/|$)') THEN 'Sweden'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.sy(/|$)') THEN 'Syria'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tw(/|$)') THEN 'Taiwan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tj(/|$)') THEN 'Tajikistan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tz(/|$)') THEN 'Tanzania'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.th(/|$)') THEN 'Thailand'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tg(/|$)') THEN 'Togo'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tk(/|$)') THEN 'Tokelau'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.to(/|$)') THEN 'Tonga'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tt(/|$)') THEN 'Trinidad & Tobago'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tn(/|$)') THEN 'Tunisia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tr(/|$)') THEN 'Turkey'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tm(/|$)') THEN 'Turkmenistan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tc(/|$)') THEN 'Turks and Caicos Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.tv(/|$)') THEN 'Tuvalu'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ug(/|$)') THEN 'Uganda'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ua(/|$)') THEN 'Ukraine'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ae(/|$)') THEN 'United Arab Emirates (UAE)'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.vi(/|$)') THEN 'United States Virgin Islands'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.uy(/|$)') THEN 'Uruguay'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.uz(/|$)') THEN 'Uzbekistan'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.vu(/|$)') THEN 'Vanuatu'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.va(/|$)') THEN 'Vatican City'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ve(/|$)') THEN 'Venezuela'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.vn(/|$)') THEN 'Vietnam'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.wf(/|$)') THEN 'Wallis and Futuna'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.eh(/|$)') THEN 'Western Sahara'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ma(/|$)') THEN 'Western Sahara'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.ye(/|$)') THEN 'Yemen'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.zm(/|$)') THEN 'Zambia'
      WHEN REGEXP_CONTAINS(page, r'(?i)\\.zw(/|$)') THEN 'Zimbabwe'
      ELSE 'Other'
    END AS gov_domain,
    is_root_page,
    performance_score,
    accessibility_score,
    best_practices_score,
    seo_score,
    wptid
  FROM
    score_data
  WHERE
    REGEXP_CONTAINS(page, r'(?i)('
      '(\\w+\\.)*\\.un\\.org(/|$)'  -- United Nations and International Organizations
      '|(\\w+\\.)*\\.worldbank\\.org(/|$)'
      '|(\\w+\\.)*\\.undp\\.org(/|$)'
      '|(\\w+\\.)*\\.reliefweb\\.int(/|$)'
      '|(\\w+\\.)*\\.who\\.int(/|$)'
      '|(\\w+\\.)*\\.unfccc\\.int(/|$)'
      '|(\\w+\\.)*\\.unccd\\.int(/|$)'
      '|(\\w+\\.)*\\.unesco\\.org(/|$)'

      '|(\\w+\\.)*\\.europa\\.eu(/|$)'  -- European Union

      '|(\\w+\\.)*\\.gov(\\.[a-z]{2,3})?(/|$)'  -- US Government and global .gov domains (e.g., .gov.uk, .gov.au)
      '|(\\w+\\.)*\\.mil(\\.[a-z]{2,3})?(/|$)'  -- US Military and global .mil domains

      '|(\\w+\\.)*\\.myflorida\\.com(/|$)' -- Florida

      '|(\\w+\\.){0,2}(gov|mil|gouv|gob|gub|go|govt|gv|nic|government)\\.(taipei|[a-z]{2})?(/|$)' -- Other generic government formats (e.g., gouv.fr, gob.mx, go.jp)

      '|(\\w+\\.)*\\.gc\\.ca(/|$)'  -- Canada and provinces
      '|(\\w+\\.)*\\.canada\\.ca(/|$)'
      '|(\\w+\\.)*\\.alberta\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.ab\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.bc\\.ca(/|$)'
      '|(\\w+\\.)*\\.manitoba\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.mb\\.ca(/|$)'
      '|(\\w+\\.)*\\.gnb\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.nb\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.nl\\.ca(/|$)'
      '|(\\w+\\.)*\\.novascotia\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.ns\\.ca(/|$)'
      '|(\\w+\\.)*\\.ontario\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.on\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.pe\\.ca(/|$)'
      '|(\\w+\\.)*\\.quebec\\.ca(/|$)'
      '|(\\w+\\.)*\\.gouv\\.qc\\.ca(/|$)'
      '|(\\w+\\.)*\\.revenuquebec\\.ca(/|$)'
      '|(\\w+\\.)*\\.saskatchewan\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.sk\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.nt\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.nu\\.ca(/|$)'
      '|(\\w+\\.)*\\.yukon\\.ca(/|$)'
      '|(\\w+\\.)*\\.gov\\.yk\\.ca(/|$)'

      '|(\\w+\\.)*\\.bund\\.de(/|$)'  -- Germany

      '|(\\w+\\.)*\\.belgium\\.be(/|$)'  -- Belgium
      '|(\\w+\\.)*\\.fgov\\.be(/|$)'
      '|(\\w+\\.)*\\.vlaanderen\\.be(/|$)'
      '|(\\w+\\.)*\\.wallonie\\.be(/|$)'
      '|(\\w+\\.)*\\.brussels\\.be(/|$)'
      '|(\\w+\\.)*\\.mil\\.be(/|$)'

      '|(\\w+\\.)*\\.gov\\.se(/|$)'  -- Sweden
      '|(\\w+\\.)*\\.1177\\.se(/|$)'
      '|(\\w+\\.)*\\.funktionstjanster\\.se(/|$)'
      '|(\\w+\\.)*\\.hemnet\\.se(/|$)'
      '|(\\w+\\.)*\\.smhi\\.se(/|$)'
      '|(\\w+\\.)*\\.sverigesradio\\.se(/|$)'
      '|(\\w+\\.)*\\.klart\\.se(/|$)'
      '|(\\w+\\.)*\\.bankid\\.com(/|$)'
      '|(\\w+\\.)*\\.synonymer\\.se(/|$)'
      '|(\\w+\\.)*\\.arbetsformedlingen\\.se(/|$)'
      '|(\\w+\\.)*\\.skatteverket\\.se(/|$)'
      '|(\\w+\\.)*\\.schoolsoft\\.se(/|$)'
      '|(\\w+\\.)*\\.postnord\\.se(/|$)'
      '|(\\w+\\.)*\\.grandid\\.com(/|$)'
      '|(\\w+\\.)*\\.viaplay\\.se(/|$)'
      '|(\\w+\\.)*\\.skola24\\.se(/|$)'
      '|(\\w+\\.)*\\.forsakringskassan\\.se(/|$)'
      '|(\\w+\\.)*\\.vklass\\.se(/|$)'
      '|(\\w+\\.)*\\.sl\\.se(/|$)'
      '|(\\w+\\.)*\\.familjeliv\\.se(/|$)'

      '|(\\w+\\.)*\\.valtioneuvosto\\.fi(/|$)'  -- Finland
      '|(\\w+\\.)*\\.minedu\\.fi(/|$)'
      '|(\\w+\\.)*\\.formin\\.fi(/|$)'
      '|(\\w+\\.)*\\.intermin\\.fi(/|$)'
      '|(\\w+\\.)*\\.suomi\\.fi(/|$)'
      '|(\\w+\\.)*\\.ym\\.fi(/|$)'
      '|(\\w+\\.)*\\.stm\\.fi(/|$)'
      '|(\\w+\\.)*\\.tem\\.fi(/|$)'
      '|(\\w+\\.)*\\.lvm\\.fi(/|$)'
      '|(\\w+\\.)*\\.mmm\\.fi(/|$)'
      '|(\\w+\\.)*\\.okm\\.fi(/|$)'
      '|(\\w+\\.)*\\.vm\\.fi(/|$)'
      '|(\\w+\\.)*\\.defmin\\.fi(/|$)'
      '|(\\w+\\.)*\\.oikeusministerio\\.fi(/|$)'
      '|(\\w+\\.)*\\.um\\.fi(/|$)'
      '|(\\w+\\.)*\\.vero\\.fi(/|$)'
      '|(\\w+\\.)*\\.kela\\.fi(/|$)'

      '|(\\w+\\.)*\\.lrv\\.lt(/|$)'  -- Lithuania
      '|(\\w+\\.)*\\.uzt\\.lt(/|$)'
      '|(\\w+\\.)*\\.migracija\\.lt(/|$)'
      '|(\\w+\\.)*\\.kam\\.lt(/|$)'
      '|(\\w+\\.)*\\.lrs\\.lt(/|$)'
      '|(\\w+\\.)*\\.urm\\.lt(/|$)'

      '|(\\w+\\.)*\\.riik\\.ee(/|$)'  -- Estonia
      '|(\\w+\\.)*\\.riigiteataja\\.ee(/|$)'
      '|(\\w+\\.)*\\.eesti\\.ee(/|$)'
      '|(\\w+\\.)*\\.valitsus\\.ee(/|$)'

      '|(\\w+\\.)*\\.admin\\.ch(/|$)'  -- Switzerland

      '|(\\w+\\.)*\\.seg-social\\.es(/|$)'  -- Spain
      '|(\\w+\\.)*\\.ine\\.es(/|$)'
      '|(\\w+\\.)*\\.boe\\.es(/|$)'

      '|(\\w+\\.)*\\.ft\\.dk(/|$)'  -- Denmark
      '|(\\w+\\.)*\\.nemkonto\\.dk(/|$)'
      '|(\\w+\\.)*\\.nemlog-in\\.dk(/|$)'
      '|(\\w+\\.)*\\.mitid\\.dk(/|$)'
      '|(\\w+\\.)*\\.digst\\.dk(/|$)'
      '|(\\w+\\.)*\\.sikkerdigital\\.dk(/|$)'
      '|(\\w+\\.)*\\.forsvaret\\.dk(/|$)'
      '|(\\w+\\.)*\\.skat\\.dk(/|$)'
      '|(\\w+\\.)*\\.stps\\.dk(/|$)'
      '|(\\w+\\.)*\\.ufm\\.dk(/|$)'
      '|(\\w+\\.)*\\.urm\\.dk(/|$)'
      '|(\\w+\\.)*\\.uvm\\.dk(/|$)'
      '|(\\w+\\.)*\\.politi\\.dk(/|$)'
      '|(\\w+\\.)*\\.dataetiskraad\\.dk(/|$)'
      '|(\\w+\\.)*\\.at\\.dk(/|$)'
      '|(\\w+\\.)*\\.kum\\.dk(/|$)'

      '|(\\w+\\.)*\\.govvrn\\.ru(/|$)' -- Russia

      '|(\\w+\\.)*\\.public\\.lu(/|$)'  -- Luxembourg
      '|(\\w+\\.)*\\.etat\\.lu(/|$)'

      '|(\\w+\\.)*\\.governo\\.it(/|$)'  -- Italy

      '|(\\w+\\.)*\\.overheid\\.nl(/|$)'  -- Netherlands
      '|(\\w+\\.)*\\.mijnoverheid\\.nl(/|$)'

      '|(\\w+\\.)*\\.govern\\.ad(/|$)'  -- Andorra
      '|(\\w+\\.)*\\.exteriors\\.ad(/|$)'
      '|(\\w+\\.)*\\.consellgeneral\\.ad(/|$)'

      ')')
)

SELECT
  gov_domain,
  page,
  is_root_page,
  performance_score,
  accessibility_score,
  best_practices_score,
  seo_score,
  wptid
FROM
  domain_scores
WHERE gov_domain IS NOT NULL
ORDER BY gov_domain;
