runtime: python37
entrypoint: gunicorn -b :$PORT main:app
default_expiration: 3h

handlers:
- url: /static/fonts/(.*\.(woff|woff2))$
  static_files: static/fonts/\1
  upload: static/fonts/.*\.(woff|woff2)$
  secure: always
  expiration: 365d

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
