###########################
## Calibre Image Action  ##
###########################
# 
# This runs the calibre GitHub action to compress our images
#
# This Action has a few different methoids for running:
# 1) For Pull Requests from and to the main repo it can run and update the PR
# 2) For pushes to main, it will run and create a new PR. This captures PR from
#    Forks.
# 3) It also runs every sunday at 11pm in case anything else sneaks in or any
#    improvements are added to Calibre. This will also open a PR if necessary.
# 4) Finally it can be kicked off manually and it will open a PR if necessary.
#
name: Compress images
on:
  schedule:
    # Run a full compression every Sunday at 11pm to start the week right
    - cron: '00 23 * * 0'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    # Only run on main repo as PRs can't be updated on forks
    if: github.repository == 'HTTPArchive/almanac.httparchive.org'
    env:
      COMPRESS_ONLY: false
    steps:
    - name: Set COMPRESS_ONLY variable to true
      # If it's not a pull request then run in compressOnly mode
      if: github.event_name != 'pull_request'
      run: |
        echo "::set-env name=COMPRESS_ONLY::true"
    - name: Checkout branch
      uses: actions/checkout@v2.3.2
    - name: calibreapp/image-actions
      id: calibre
      uses: calibreapp/image-actions@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        compressOnly: ${{ env.COMPRESS_ONLY }}
        jpegProgressive: true
    - name: Create Pull Request
      # If it's not a pull request then commit any changes as a new PR
      if: |
        github.event_name != 'pull_request' &&
        steps.calibre.outputs.markdown != ''
      id: cpr
      uses: peter-evans/create-pull-request@v3.3.0
      with:
        title: Auto Compress Images
        branch-suffix: timestamp
        commit-message: Compress Images
        body: ${{ steps.calibre.outputs.markdown }}
        labels: performance
