###########################
## Calibre Image Action  ##
###########################
# 
# This runs the calibre GitHub action to compress our images
#
# This Action has a few limitations:
#
# 1) This currently only works on pull requests from this repo
#    and fails silently for PRs from forks. We've added a PR
#    to handle this better (https://github.com/calibreapp/image-actions/pull/54)
#    and after that can probably combine to the generate_chapters.yml.
#
# 2) It seems to only do a basic level of optimisations and better results can
#    be achieved from https://tinypng.com/ or https://squoosh.app/ but not as automated
#    so still good to have this.
#
# 3) Currently doesn't handle WebP (https://github.com/calibreapp/image-actions/issues/31)
#
name: Compress images
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks as they don't work
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
