name: Run Python Tests
on:
  workflow_dispatch:
  push:
    paths:
      - src/config/**
      - src/**.py
      - src/requirements.txt
  pull_request:
    paths:
      - src/config/**
      - src/**.py
      - src/requirements.txt
jobs:
  tests:
    name: Run pytest
    # Skip duplicate job for local branches
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          cd src
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          cd src
          pytest
