name: Run Python Tests
on:
  workflow_dispatch:
jobs:
  tests:
    name: Run pytest
    # Skip duplicate job for local branches
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.1.3
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          cd src
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          cd src
          pytest
